#!/bin/bash

TOP_DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo 'Creating the external workspace'
cd ${TOP_DIR}/external
if [ ! -d "./src" ]; then
  wstool init src
fi
catkin_make_isolated --install --cmake-args -DCMAKE_BUILD_TYPE=Release
touch ${TOP_DIR}/external/install_isolated/.catkin
if [ -d "${TOP_DIR}/external/install_isolated/setup.bash" ]; then
  source ${TOP_DIR}/external/install_isolated/setup.bash
fi

echo 'Creating the internal workspace'
cd ${TOP_DIR}/internal
if [ ! -d "./src" ]; then
  wstool init src
fi
catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release

if [ -d "${TOP_DIR}/internal/devel/setup.bash" ]; then
  source ${TOP_DIR}/internal/devel/setup.bash --extend
fi
